### ISSUE TITLE
Support for cluster

### ISSUE THREAD

**Issue by lcacciagioni** [rafaeljusto/redigomock#19]
Any plans to support github.com/chasex/redis-go-cluster? It can be a killer feature

**Comment by rafaeljusto** [comment]
The library github.com/chasex/redis-go-cluster says:

> redis-go-cluster has compatible interface to Redigo

but it does not work with `redis.Conn` interface. And as the `redis.NewCluster` returns a concrete type with only unexported fields instead of an interface, it makes it difficult to create mocks. If you have any ideas on how to modify this library to allow it to mock both libraries (redigo and redis-go-cluster), we are accepting pull requests :smile:
